### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Greensky-gs** [Greensky-gs/lofi-mobile#1]
Here is the list of the things I have to do in the app before I forget (feel free to add more by commenting)

**__Important__**

- [x] Fix song addition when a playlist is played : create a method "playlist add" that add the songs at the beginning of the track list

- [x] Fix song switching (sometimes it create a new player so songs are played at the same time) : usually happens when a song is played from the playlist details page)

- [x] When a song is played from a playlist, add the following songs to the queue

- [ ] Add durations to stations

- [x] Fix popup play button's tint

- [x] Dark theme

- [ ] ~~ Make the app offline ~~

- [x] Fix bottom of home page (the last station isn't displayed correctly, add the heigth of the navigation

**__Todo, but not immediately__**

- [ ] Make swip feature (swip to the right to change to home/search, etc)

- [ ] Make an edit name for playlists

- [ ] Hide the navigation bar on loading
